server:
  port: 8081

spring:
  application:
    name: estoqueproduto
  datasource:
    url: jdbc:h2:file:~/estoque-compartilhado/db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5671
    username: gqkaxsna
    password: A9kXlajE8sVzMwlOn92cPVb3AsZcNFMm
    virtual-host: gqkaxsna
    ssl:
      enabled: true
